virtio-devices: seccomp: Add seccomp filters for balloon/mem/vhost worker threads
cloud-hypervisor/cloud-hypervisor pull request #1618
Opened 2020-08-18 06:16 UTC by likebreath

This patch enables the seccomp filters for the balloon/mem/vhost worker thread.

Partially fixes: #925

Signed-off-by: Bo Chen <chen.bo@intel.com>

2020-08-18 06:50 UTC, likebreath commented
One test is failing, and I will look into it tomorrow.

2020-08-18 17:18 UTC, likebreath commented
For now the only test that is being failing is `test_vhost_user_net_tap_multiple_queues` for both AArch64 and MUSL build. Also, it is only failing w/ MMIO feature enabled for both platforms. My local tests are working fine, and did not report missing syscalls. After all, it should be an issue of missing syscalls in the allowed list. I will try to locate it, maybe by using custom signal handlers.

2020-08-18 18:35 UTC, likebreath commented
I found a missing syscall from the `vhost_net_ctl` worker thread and now the CI is only failing on the `AArch64` build worker for `tests::parallel::test_vhost_user_net_multiple_queues` when `mmio` feature is enabled. Any advises on how to move forward? @sboeuf @michael2012z @MrXinWang

2020-08-19 00:40 UTC, michael2012z requested changes
With the help of GDB, I was able to capture where the BAD syscall is:

```
Thread 12 "vhost_net" received signal SIGSYS, Bad system call.
[Switching to Thread 0xfffff690df10 (LWP 160559)]
__lll_lock_wait (futex=futex@entry=0xfffff0002510, private=0) at lowlevellock.c:45
45	lowlevellock.c: No such file or directory.
(gdb) bt
#0  __lll_lock_wait (futex=futex@entry=0xfffff0002510, private=0) at lowlevellock.c:45
#1  0x0000fffff7f6d7d4 in __GI___pthread_mutex_lock (mutex=0xfffff0002510) at pthread_mutex_lock.c:78
#2  0x0000aaaaaad720d0 in std::sys::unix::mutex::Mutex::lock (self=0xfffff0002510)
    at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd/src/libstd/sys/unix/mutex.rs:57
#3  0x0000aaaaaad68ea8 in std::sys_common::mutex::Mutex::raw_lock (self=0xfffff0002510)
    at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd/src/libstd/sys_common/mutex.rs:41
```

Looking into file lowlevellock.c (here is a link for the file, but may not be the exact version used in our test: https://fossies.org/dox/glibc-ports-2.16.0/arm_2nptl_2lowlevellock_8c_source.html), futex is involved in the subroutine `__lll_lock_wait`.

So, allowing syscall `SYS_futex` should resolve the test failure.

2020-08-19 00:40 UTC, michael2012z commented on virtio-devices/src/seccomp_filters.rs
> +    ])
Adding `allow_syscall(libc::SYS_futex),` fixes the failure of test case `test_vhost_user_net_multiple_queues`

2020-08-19 03:31 UTC, likebreath commented
Great. The CI now is passing. Thanks again. PTAL. @michael2012z @sboeuf

2020-08-19 04:47 UTC, michael2012z approved these changes

2020-08-19 05:25 UTC, michael2012z commented
LGTM. 
Please have a look, @sboeuf .

2020-08-19 06:33 UTC, sboeuf approved these changes

2020-08-19 06:33 UTC, merged