ci: Move back to latest virtiofsd version
cloud-hypervisor/cloud-hypervisor pull request #1742
Opened 2020-09-23 16:46 UTC by sboeuf

This commit moves back to the branch "virtio-fs-dev" from virtiofsd, as
we figured the changes needed to use this branch and the requirements
from the new meson build from QEMU.

This is a partial fix as we expect the missing python3-setuptools
package to be directly part of the Docker container. Until we fix the
container, we must install manually the missing package.

Signed-off-by: Sebastien Boeuf <sebastien.boeuf@intel.com>

2020-09-25 04:11 UTC, likebreath approved these changes

2020-09-25 09:23 UTC, rbradford requested changes
I think the container should be updated instead.

2020-09-25 09:57 UTC, sboeuf commented
@rbradford 
>I think the container should be updated instead.

Yes I agree, I'll work on it this afternoon.

2020-09-30 10:29 UTC, sboeuf commented
@rbradford this should be ready to be merged :)

2020-09-30 12:10 UTC, rbradford approved these changes

2020-09-30 12:10 UTC, merged