virtio-mem: Add support for backing file
cloud-hypervisor/cloud-hypervisor pull request #1876
Opened 2020-10-18 09:36 UTC by teawater

Current virtio-mem is not set backing file when call create_ram_region
and call fallocate64 incorrently.

This commit setup backing file when call create_ram_region.
And corrent the code that call fallocate64.

Signed-off-by: Hui Zhu <teawater@antfin.com>

2020-10-19 07:04 UTC, sboeuf requested changes
@teawater I'd like to discuss the use cases associated with the pull request:
- What are you trying to solve exactly?
- What would be the CH command line that was not working as expected?

Before going further into the details of this pull request I would appreciate if you could explain the use cases that would need this fix.
I'm not sure you're correctly solving the problem here, because we always create a static zone along with a dedicated virtio-mem region. So that means `--memory-zone size=1G,hotplug_size=3G,file=/foo/bar` will create a region of 1G along with a virtio-mem region of 3G (starting at 4G in the address space). This is challenging to `mmap()` the file into each region, and I'm not even sure that's what the user should expect.

2020-10-19 09:04 UTC, teawater commented
@sboeuf With support of backing file, virtio-mem can work together with hugetlbfs.

For example:
```
--memory-zone id=m0,size=128M id=m1,size=0,hotplug_size=100G,file=/dev/hugepages
```
Without backing file support, m1 will use normal memory.  With this support, m1 will use hugepages.

2020-10-19 09:48 UTC, sboeuf commented
@teawater 
>With support of backing file, virtio-mem can work together with hugetlbfs.

I agree that would be nice to add hugetlbfs support, but I'd like to see that happening using the `hugepages=on` option from CH:
```
--memory-zone id=m1,size=1G,hotplug_size=100G,hugepages=on
```
This way, we don't bring the potential complexity of having to split the memory mapping of a file over multiple memory regions.

And with the same idea in mind, we can make the `virtio-mem` region as `MAP_SHARED` by relying on `shared=on`:
```
--memory-zone id=m1,size=1G,hotplug_size=100G,shared=on
```
For now, these should be enough to solve the limitation you're bringing up here.

2020-10-19 10:27 UTC, teawater commented
> @teawater
> 
> > With support of backing file, virtio-mem can work together with hugetlbfs.
> 
> I agree that would be nice to add hugetlbfs support, but I'd like to see that happening using the `hugepages=on` option from CH:
> 
> ```
> --memory-zone id=m1,size=1G,hotplug_size=100G,hugepages=on
> ```
> 
> This way, we don't bring the potential complexity of having to split the memory mapping of a file over multiple memory regions.
> 
> And with the same idea in mind, we can make the `virtio-mem` region as `MAP_SHARED` by relying on `shared=on`:
> 
> ```
> --memory-zone id=m1,size=1G,hotplug_size=100G,shared=on
> ```
> 
> For now, these should be enough to solve the limitation you're bringing up here.

I am really sure because:
1.  hugetlbfs dir is mounted by user.  They can use any dir.  For example:
mount -t hugetlbfs hugetlbfs /dev/hugepages

2. hugetlbfs is just normal backing file like others.  Normal memory sets hugetlbfs to use hugepage.  Add a special option to open it for virtio-mem are confusing.



> @teawater I'd like to discuss the use cases associated with the pull request:
> 
> * What are you trying to solve exactly?
> * What would be the CH command line that was not working as expected?
> 
> Before going further into the details of this pull request I would appreciate if you could explain the use cases that would need this fix.
> I'm not sure you're correctly solving the problem here, because we always create a static zone along with a dedicated virtio-mem region. So that means `--memory-zone size=1G,hotplug_size=3G,file=/foo/bar` will create a region of 1G along with a virtio-mem region of 3G (starting at 4G in the address space). This is challenging to `mmap()` the file into each region, and I'm not even sure that's what the user should expect.

Sorry I forgot to answer this question in the last comments.
When the memory manager map the backing file, it uses an argument file_offset to map the region to the different file path.
```
                let region = MemoryManager::create_ram_region(
                    &zone.file,
                    file_offset,
                    region_start,
                    region_size,
                    prefault,
                    zone.shared,
                    zone.hugepages,
                    zone.host_numa_node,
                    &ext_regions,
                )?;
```
I updated the code to get the tail address of the map and save it in file_offset_tail.

When it map the backing file for virtio-mem, it will use file_offset_tail as the file offset.
```
                        let region = MemoryManager::create_ram_region(
                            &zone.file,
                            file_offset_tail,
                            start_addr,
                            hotplug_size as usize,
                            false,
                            zone.shared,
                            zone.hugepages,
                            zone.host_numa_node,
                            &None,
                        )?;
                        file_offset_tail += hotplug_size;
```

2020-10-19 11:40 UTC, sboeuf commented
@teawater I'm not suggesting to create new options, but to use the existing ones. Both `shared=on|off` and `hugepages=on|off` are options of `--memory-zone` parameter. You don't need to provide any file, simply provide `zone.shared` and `zone.hugepages` to `create_ram_region()`. In case of `hugepages=on`, memory will be allocated with `MFD_HUGETLB` and `MAP_HUGE_2MB`, and in case of `shared=on` memory will be allocated with `MAP_SHARED` flag.
I think this is enough for now, unless you have something else in mind.

2020-10-20 01:21 UTC, teawater commented
> @teawater I'm not suggesting to create new options, but to use the existing ones. Both `shared=on|off` and `hugepages=on|off` are options of `--memory-zone` parameter. You don't need to provide any file, simply provide `zone.shared` and `zone.hugepages` to `create_ram_region()`. In case of `hugepages=on`, memory will be allocated with `MFD_HUGETLB` and `MAP_HUGE_2MB`, and in case of `shared=on` memory will be allocated with `MAP_SHARED` flag.
> I think this is enough for now, unless you have something else in mind.

MFD_HUGETLB let kernel use "Transparent HugePage"(https://www.kernel.org/doc/Documentation/vm/transhuge.txt).
Hugetlbfs let kernel use "huge page" (https://www.kernel.org/doc/Documentation/vm/hugetlbpage.txt).

2020-10-20 06:59 UTC, sboeuf commented
@teawater 
>MFD_HUGETLB let kernel use "Transparent HugePage"(https://www.kernel.org/doc/Documentation/vm/transhuge.txt).
Hugetlbfs let kernel use "huge page" (https://www.kernel.org/doc/Documentation/vm/hugetlbpage.txt).

Yes I read it, and basically THP is a better huge page. I don't see why you wouldn't want to use it.
```
Transparent Hugepage Support is an alternative means of
using huge pages for the backing of virtual memory with huge pages
that supports the automatic promotion and demotion of page sizes and
without the shortcomings of hugetlbfs.
```

2020-10-21 01:56 UTC, teawater commented
> @teawater
> 
> > MFD_HUGETLB let kernel use "Transparent HugePage"(https://www.kernel.org/doc/Documentation/vm/transhuge.txt).
> > Hugetlbfs let kernel use "huge page" (https://www.kernel.org/doc/Documentation/vm/hugetlbpage.txt).
> 
> Yes I read it, and basically THP is a better huge page. I don't see why you wouldn't want to use it.
> 
> ```
> Transparent Hugepage Support is an alternative means of
> using huge pages for the backing of virtual memory with huge pages
> that supports the automatic promotion and demotion of page sizes and
> without the shortcomings of hugetlbfs.
> ```

Normal HP can store hugepages to pool.  It ensures the success rate of memory allocation when it is actually used.

2020-10-22 16:01 UTC, rbradford commented
`mem_createfd()` with `MFD_HUGETLB` uses hugetlbfs (i.e. explicit huge pages) *not* transparent huge pages which is thus equivalent of using a filesystem backed by hugetlbfs. Therefore your problem can be solved by `hugepages=on` so I don't think we should add this complexity.

2020-10-23 01:28 UTC, teawater commented
> `memfd_create()` with `MFD_HUGETLB` uses hugetlbfs (i.e. explicit huge pages) _not_ transparent huge pages which is thus equivalent of using a filesystem backed by hugetlbfs. Therefore your problem can be solved by `hugepages=on` so I don't think we should add this complexity.

MFD_HUGETLB (since Linux 4.14) is not support by some kernel on my hand.

2020-10-23 08:07 UTC, sboeuf commented
>MFD_HUGETLB (since Linux 4.14) is not support by some kernel on my hand.

4.14 was released on Nov 12th 2017, I don't think we want to make some decisions on the VMM's implementation based on kernels older than 3 years.

2020-10-23 08:26 UTC, rbradford commented
> > MFD_HUGETLB (since Linux 4.14) is not support by some kernel on my hand.
> 
> 4.14 was released on Nov 12th 2017, I don't think we want to make some decisions on the VMM's implementation based on kernels older than 3 years.

I agree. This project is all about avoiding legacy functionality and that includes expecting a reasonably modern host OS.

I'm also not sure what happens if you use this change with an arbitrary file (vs a hugetlbfs directory)

2020-10-26 02:44 UTC, teawater commented
Open https://github.com/cloud-hypervisor/cloud-hypervisor/pull/1909 to handle the issue.

2020-10-26 02:44 UTC, closed without merging