tests: Add integration test `test_mavctap`
cloud-hypervisor/cloud-hypervisor pull request #2262
Opened 2021-02-10 20:13 UTC by likebreath

This integration test mimics the instructions from
`docs/macvtap-bridge.md`.

Fixes: #2215

Signed-off-by: Bo Chen <chen.bo@intel.com>

2021-02-10 20:46 UTC, likebreath commented
The added integration test is passing, but the GH actions are complaining. Let me restart these actions, and see how that goes.

```
sh -c git checkout eb53215d5eac28157d53aeb08141d8315eeb71cb; cargo check --all --target=x86_64-unknown-linux-gnu 
Previous HEAD position was 7619e826 Merge eb53215d5eac28157d53aeb08141d8315eeb71cb into 9af477e9647a0c1c315957b413b9d04f446dd67d
HEAD is now at eb53215d tests: Add integration test `test_mavctap`
    Updating git repository `https://github.com/cloud-hypervisor/kvm-ioctls`
error: failed to get `kvm-ioctls` as a dependency of package `hypervisor v0.1.0 (/home/runner/work/cloud-hypervisor/cloud-hypervisor/hypervisor)`

Caused by:
  failed to load source for dependency `kvm-ioctls`

Caused by:
  Unable to update https://github.com/cloud-hypervisor/kvm-ioctls?branch=ch#64427395

Caused by:
  object not found - no match for id (64427395b60e00403aed3026362a1b19873230e6); class=Odb (9); code=NotFound (-3)
Error: Process completed with exit code 123.
```

2021-02-11 11:34 UTC, rbradford requested changes

2021-02-11 11:34 UTC, rbradford commented on tests/integration.rs
> +            tap_index.truncate(tap_index.len() - 1); // Remove the tailing '/newline'
does `.trim()` not work?

2021-02-11 11:34 UTC, rbradford commented on tests/integration.rs
> +                    format!("{}\0", tap_device).as_ptr() as *const std::os::raw::c_char,
`std::ffi:CString::new(tap_device).unwrap().as_ptr()`

2021-02-11 15:25 UTC, rbradford approved these changes

2021-02-11 15:25 UTC, merged