docs: update hotplug.md
cloud-hypervisor/cloud-hypervisor pull request #3505
Opened 2021-12-27 01:34 UTC by LiangZhou-CTY

Currently cloud-hypervisor supports hotplug of CPUs, passthrough devices, virtio devices and memory resizing, 
but in hotplug.md it still mentiones: "Currently Cloud Hypervisor only supports hot plugging of CPU devices."
We need to remove the incorrect information from hotplug.md to reflect the true situation.

Fixes: #3504

Signed-off-by: Liang Zhou <zhoul110@chinatelecom.cn>

2021-12-27 02:43 UTC, MrXinWang commented
Hi @LiangZhou-CTY, could you please update the latest status instead of just deleting the incorrect ones? Thanks!

You can put what you write in commit message to this section. Also please also add "currently the vCPU hotplug is not supported on AArch64". Thanks!

2021-12-27 03:10 UTC, LiangZhou-CTY commented
> Hi @LiangZhou-CTY, could you please update the latest status instead of just deleting the incorrect one? Thanks!
> 
> You can put what you write in commit message ("Currently cloud-hypervisor supports hotplug of CPUs, passthrough devices, virtio devices and memory resizing") to this section. Also please also add "currently the vCPU hotplug is not supported on AArch64". Thanks!

@MrXinWang  Sure, updated.  Thanks.

2021-12-27 03:27 UTC, MrXinWang approved these changes
Looks good from my side, I will wait other people's especially the x86 maintainers' opinion.

2022-01-03 09:31 UTC, sboeuf requested changes

2022-01-03 09:31 UTC, sboeuf commented on docs/hotplug.md
> +Currently cloud-hypervisor supports hotplug of CPUs (except for AArch64), passthrough devices, virtio devices and memory resizing.
```suggestion
Currently Cloud Hypervisor supports hot plugging of CPUs devices (x86 only), PCI devices and memory resizing.
```

2022-01-17 08:13 UTC, sboeuf commented
@LiangZhou-CTY any update on this? Could you please address the comments so that we can go ahead and merge this PR.

2022-01-17 09:04 UTC, sboeuf approved these changes

2022-01-17 09:43 UTC, merged