Enable direct kernel boot when firmware boot on aarch64
cloud-hypervisor/cloud-hypervisor pull request #4426
Opened 2022-08-04 08:26 UTC by jongwu

What's direct kernel boot in firmware boot?

- Currently, when VM start from firmware, it must retrieve kernel from disk. Direct kernel boot means loading kernel specified by command line parameter like "-kernel". E.g, start a VM using Qemu, using both "-kernel", to load kernel, and "-bios", to load firmware.

How to implement it in this PR?

- To offer both firmware image and kernel image in the same time, we need introduce a new parameter "-firmware" accompanying with "-kernel" to do this.
- We need a mechanism to pass kernel image to firmware. Here, kernel is stored into guest memory then use fdt to pass kernel info, including memory base and size, to firmware.

Limited:

- As fdt is not used for x86, this implementation is only for aarch64.

TODO:

- Enable it for x86.
- Change the old firmware boot to this new way in the integration test.

2022-08-04 13:39 UTC, rbradford requested changes
@jongwu I acknowledge that English is not your native language and I apologise if the feedback on #4376 wasn't clear enough and I regret that you've invested time in something that I don't think should be integrated.

The correct solution to your problem (direct kernel boot with ACPI tables) is not to recreate the legacy approach used by QEMU where you have to boot a firmware and from that firmware load a kernel into the guest using a sideband method. This approach is flawed since you still have the time overhead of running most of the firmware; only the bootloader on the disk is skipped.

The correct solution is to load the kernel into the guest RAM directly and and provide a pointer to the ACPI RSDP. Some potential approaches (all of which require kernel changes)

1. Adopt PVH (or something like it) for aarch64 - we already have support for loading the ELF binary and filling in the correct fields in a PVH header
2. Pass the ACPI pointer through an entry in the FDT
3. Hard code the ACPI RSDP at a specific location

I believe the last two can be accomplished with trivial patches to our reference kernel although I think the first approach is the most likely to land upstream.

We are so close to having a solution as we already have something that works on x86-64 and on aarch64 we are only lacking passing the ACPI RSDP address.

2022-08-05 01:45 UTC, jongwu commented
Hello @rbradford -, I know what you mean but it's not the standard way to enable ACPI without firmware on aarch64. Quotes from kernel [docs(:](https://www.kernel.org/doc/html/latest/arm64/arm-acpi.html#booting-using-acpi-tables)

> The only defined method for passing ACPI tables to the kernel on ARMv8 is via the UEFI system configuration table. Just so it is explicit, this means that ACPI is only supported on platforms that boot via UEFI.

So we can't enable ACPI by just passing the RSDP address, also for now, kernel doesn't support it on aarch64.  That's say we need firmware to load and boot kernel to support ACPI.

2022-08-05 06:45 UTC, sboeuf commented
> Hello @rbradford -, I know what you mean but it's not the standard way to enable ACPI without firmware on aarch64. Quotes from kernel [docs(:](https://www.kernel.org/doc/html/latest/arm64/arm-acpi.html#booting-using-acpi-tables)
> 
> > The only defined method for passing ACPI tables to the kernel on ARMv8 is via the UEFI system configuration table. Just so it is explicit, this means that ACPI is only supported on platforms that boot via UEFI.
> 
> So we can't enable ACPI by just passing the RSDP address, also for now, kernel doesn't support it on aarch64. That's say we need firmware to load and boot kernel to support ACPI.

We know it's not available right now in the kernel, but that's why we're suggesting that you should submit a patch to the upstream kernel to support the PVH approach so that we can have an identical way of performing direct kernel boot on both x86_64 and aarch64.

2022-08-05 08:04 UTC, jongwu commented
Hello @sboeuf -, IMO, I don't think PVH is the remedy for us. If PVH only pass RSDP to kernel, what's the difference with "CONFIG_CMDLINE". Even no PVH support on aarch64, we can use "CONFIG_CMDLINE" instead to pass RSDP. But it doesn't work on aarch64, kernel will panic or boot up without ACPI with "acpi_rsdp=xxx,acpi=on" in command line. 

The kernel doc said: "The only defined method for passing ACPI tables to the kernel on ARMv8 is via the UEFI system configuration table",  I think that mean we can't pass ACPI table in other way including command line, maybe also PVH.

I will check it further for UEFI/ACPI experts on Arm and give some update later.

2022-08-05 08:12 UTC, sboeuf commented
> Hello @sboeuf -, IMO, I don't think PVH is the remedy for us. If PVH only pass RSDP to kernel, what's the difference with "CONFIG_CMDLINE". Even no PVH support on aarch64, we can use "CONFIG_CMDLINE" instead to pass RSDP. But it doesn't work on aarch64, kernel will panic or boot up without ACPI with "acpi_rsdp=xxx,acpi=on" in command line.
> 
> The kernel doc said: "The only defined method for passing ACPI tables to the kernel on ARMv8 is via the UEFI system configuration table", I think that mean we can't pass ACPI table in other way including command line, maybe also PVH.
> 
> I will check it further for UEFI/ACPI experts on Arm and give some update later.

Yes please check with experts on the topic as we need to get to the bottom of this before making any further decision. We need to understand if there's a strong technical reason for ARM to support ACPI only with EFI.

2022-08-05 13:51 UTC, jongwu commented
Hello @sboeuf @rbradford -, I consult this issue with the UEFI/ACPI expert Ard Biesheuvel. He said that we can only support ACPI via UEFI boot on aarch64. I will quote his words if I get his permission.

2022-08-05 14:44 UTC, sboeuf commented
Hi @ardbiesheuvel, we're trying to understand why the kernel documentation (and therefore implementation) states that ACPI is only supported on platforms that boot via UEFI (for `aarch64`)?

I'm trying to understand if there is a technical limitation or if this is just because nobody ever took the time to implement ACPI support for `aarch64` without UEFI boot.

2022-08-05 14:48 UTC, ardbiesheuvel commented
No, it is a deliberate decision. The ACPI spec defines only one way to discover the root table, which is via a UEFI configuration table. We also assume in many places in the ACPI code that the EFI memory map is available. (The same applies for SMBIOS, by the way).

So if you want to boot arm64 in ACPI mode, you need to provide a minimal EFI implementation that is sufficient to run the EFI stub. Otherwise, you can always boot via DT.

2022-08-05 14:52 UTC, sboeuf commented
> No, it is a deliberate decision. The ACPI spec defines only one way to discover the root table, which is via a UEFI configuration table. We also assume in many places in the ACPI code that the EFI memory map is available. (The same applies for SMBIOS, by the way).
> 
> So if you want to boot arm64 in ACPI mode, you need to provide a minimal EFI implementation that is sufficient to run the EFI stub. Otherwise, you can always boot via DT.

Linux can be built as a PVH ELF binary so that it carries the location of the RSDP, and this is something supported on x86_64. I don't follow why we couldn't propose such design to be implemented for aarch64 as well?

2022-08-05 14:57 UTC, ardbiesheuvel commented
You are free to propose such a design, of course. But not everything that x86 does is a good idea, and actually, the ACPI and SMBIOS specs do have special provisions for x86 to discover the tables from bare memory, but this does not work on ARM because it does not have a unified architected memory map like x86 does.

I am aware that this is not the same as passing the RSDP pointer directly, but that doesn't make it a good idea from maintainability point of view. If non-EFI ACPI boot is an important use case, let's take it up with the ARM architects and the UEFI forum to come up with something that is not a point fix for Linux+cloudhv.

2022-08-05 15:12 UTC, sboeuf commented
> You are free to propose such a design, of course. But not everything that x86 does is a good idea, and actually, the ACPI and SMBIOS specs do have special provisions for x86 to discover the tables from bare memory, but this does not work on ARM because it does not have a unified architected memory map like x86 does.
> 
> I am aware that this is not the same as passing the RSDP pointer directly, but that doesn't make it a good idea from maintainability point of view. If non-EFI ACPI boot is an important use case, let's take it up with the ARM architects and the UEFI forum to come up with something that is not a point fix for Linux+cloudhv.

I think the idea is to provide a unified mechanism for direct kernel boot not matter which architecture you rely on when running a virtual machine. And the fact that we need a firmware to be able to boot with ACPI tables on ARM sounds like it's forcing an extra layer to be involved when it's not technically needed.

I don't know who should be involved on this discussion from the ARM architects and UEFI stakeholders, but please don't hesitate to CC these folks on this thread, or maybe share some names so that we can start a thread over email :)

@michael2012z @MrXinWang maybe you know who could be contacted for such discussion.

2022-08-05 15:18 UTC, ardbiesheuvel commented
> I think the idea is to provide a unified mechanism for direct kernel boot not matter which architecture you rely on when running a virtual machine.

I'm sorry but this is a fiction. Arch-agnostic direct kernel boot does not exist, you will need to carry code for each architecture that understands where the kernel may be loaded, where the initrd may be loaded, where the command line may be loaded, etc. etc. This is the whole point of EFI, to keep this Linux+arch specific knowledge in Linux where it belongs.

Note that EFI firmware for CloudHv already exists, but I guess it will need to be ported to ARM. This is also what we did in the past for QEMU, Xen and KvmTool.

> And the fact that we need a firmware to be able to boot with ACPI tables on ARM sounds like it's forcing an extra layer to be involved when it's not technically needed.
> 

It is technically needed. ACPI on Linux/arm64 relies on the EFI memory map and other EFI specific facilities.

> I don't know who should be involved on this discussion from the ARM architects and UEFI stakeholders, but please don't hesitate to CC these folks on this thread, or maybe share some names so that we can start a thread over email :)
> 
> @michael2012z @MrXinWang maybe you know who could be contacted for such discussion.

2022-08-05 15:41 UTC, sboeuf commented
> > I think the idea is to provide a unified mechanism for direct kernel boot not matter which architecture you rely on when running a virtual machine.
> 
> I'm sorry but this is a fiction. Arch-agnostic direct kernel boot does not exist, you will need to carry code for each architecture that understands where the kernel may be loaded, where the initrd may be loaded, where the command line may be loaded, etc. etc. This is the whole point of EFI, to keep this Linux+arch specific knowledge in Linux where it belongs.

/cc @rbradford 
> 
> Note that EFI firmware for CloudHv already exists, but I guess it will need to be ported to ARM. This is also what we did in the past for QEMU, Xen and KvmTool.

Yes there's an OVMF firmware for Cloud Hypervisor for both `x86_64` and `aarch64`. But the way OVMF expects to retrieve information about kernel and command line is through `fw_cfg`, which is very much QEMU specific. That's why we started this conversation in the first place, trying to avoid having to implement such non standard mechanism.

> 
> > And the fact that we need a firmware to be able to boot with ACPI tables on ARM sounds like it's forcing an extra layer to be involved when it's not technically needed.
> 
> It is technically needed. ACPI on Linux/arm64 relies on the EFI memory map and other EFI specific facilities.
> 
> > I don't know who should be involved on this discussion from the ARM architects and UEFI stakeholders, but please don't hesitate to CC these folks on this thread, or maybe share some names so that we can start a thread over email :)
> > @michael2012z @MrXinWang maybe you know who could be contacted for such discussion.

2022-08-05 15:53 UTC, rbradford commented
> Note that EFI firmware for CloudHv already exists, but I guess it will need to be ported to ARM. This is also what we did in the past for QEMU, Xen and KvmTool.

There is already an EFI firmware that works with Cloud Hypervisor on aarch64 and supports ACPI required functionality like device hotplug.

The complaint that is the origin of this issue is that it is "too slow" to boot the kernel within the disk image via OVMF + boot loader.

I don't believe that all the complexity that trying to implement present the kernel from the VMM (bypassing the bootloader) is worth it. I've not seen any numbers for time spent to get to OVMF, boot loader and then the kernel. It's quite possible that the bootloader is simply waiting for input a timeout.

It's a shame we can't support ACPI on aarch64 with our direct kernel boot support but I think a reasonable compromise for keeping our codebase simple.

2022-08-05 15:57 UTC, ardbiesheuvel commented
> The complaint that is the origin of this issue is that it is "too slow" to boot the kernel within the disk image via OVMF + boot loader.
> 

As a data point, booting a EFI/KVM/arm64 based VM into GRUB on Raspberry Pi 4 takes 0.4 seconds with the various user input timeouts set to 0.

2022-08-06 06:13 UTC, jongwu commented
@rbradford -, Apart from boot time, another strong reason is for Kata. Kata use direct kernel boot and there is no kernel in kata image. We can't use ACPI in kata based on Cloud Hypervisor without this feature.

2022-08-06 08:10 UTC, ardbiesheuvel commented
> @rbradford -, Apart from boot time, another strong reason is for Kata. Kata use direct kernel boot and there is no kernel in kata image. We can't use ACPI in kata based on Cloud Hypervisor without this feature.

Given that you already have an EFI implementation for CloudHv guests on arm64, it should be trivial to enable direct kernel boot on it without relying on fwcfg: just stick the kernel image in a read-only memslot, and load it from a MemoryMap(...) device path in EFI.

2022-08-06 08:14 UTC, jongwu commented
> > @rbradford -, Apart from boot time, another strong reason is for Kata. Kata use direct kernel boot and there is no kernel in kata image. We can't use ACPI in kata based on Cloud Hypervisor without this feature.
> 
> Given that you already have an EFI implementation for CloudHv guests on arm64, it should be trivial to enable direct kernel boot on it without relying on fwcfg: just stick the kernel image in a read-only memslot, and load it from a MemoryMap(...) device path in EFI.

That's what this PR does, I think.

2022-08-06 13:25 UTC, rbradford commented
Okay, it looks like the only option we have is to support direct booting via the firmware and thus requiring multiple payloads. We worked hard to avoid this by making our other firmware types like OVMF and hypervisor-fw support PVH so that only a single entry point was needed for loading and booting as well as only a single command line option.

I've opened an issue at #4445 for discussion of the requirements. Thank you to everyone who participated in the discussion on the PR. I'm closing this PR for now as the discussion needed to be completed (and implemented) on #4445 first.

2022-08-06 13:25 UTC, closed without merging