rpm: doc: Remove bundled SPEC and update README
cloud-hypervisor/cloud-hypervisor pull request #4603
Opened 2022-09-11 12:11 UTC by weltling

Closes #4257.

[ci skip]

Signed-off-by: Anatol Belski <anbelski@linux.microsoft.com>

2022-09-12 17:08 UTC, likebreath approved these changes
Thank you for the contribution. LGTM. 

Only one nit for the commit message: please use `Fixes: #4257` if that issue is resolved by this PR.

2022-09-12 18:02 UTC, weltling commented
ACK, changed as suggested in both commit message and PR description. Thanks for the checks!

2022-09-14 07:51 UTC, sboeuf requested changes
Could you please provide an extensive commit message explaining why we're removing the SPEC files from this repo. I know we can find the information in the Github issue, but from a `git log` perspective it's always good to be able to understand the rationale behind a patch.

2022-09-14 07:51 UTC, sboeuf commented on README.md
> +[obs-packaging](https://github.com/cloud-hypervisor/obs-packagin) repository.
```suggestion
[obs-packaging](https://github.com/cloud-hypervisor/obs-packaging) repository.
```

2022-09-14 07:51 UTC, sboeuf commented on README.md
> +  - [Use Prebuilt Binaries](#use-obs-packages)
```suggestion
- [Use Prebuilt Binaries](#use-prebuilt-binaries)
```

2022-09-14 13:53 UTC, weltling commented
Thanks for the review. I've applied the fixes, rebased and put more info in the commit message.

Thanks

2022-09-15 09:19 UTC, merged