Refactor VCPU creation
cloud-hypervisor/cloud-hypervisor pull request #4957
Opened 2022-11-30 12:45 UTC by jinankjain

Currently vCPUs creation is tied to memory manager which implies guest memory must be allocated and mapped before creating vCPUs. I would like to propose, let's untangle vCPU creation from memory manager. This is a requirement for MSHV to create SEV-SNP enabled VMs.

By changing this workflow we should not affect any of the existing use cases.

2022-11-30 16:00 UTC, rbradford requested changes
Perhaps this should be discussed on the GitHub issue rather than as PR. I'm sure there are alternative approaches to initialising CpuManager before MemoryManager.

2022-11-30 16:32 UTC, jinankjain commented
@rbradford Should I open a Github issue to discuss alternatives to initialize CpuManager before MemoryManager? Or we can continue the discussion as part of this PR?

2022-11-30 16:52 UTC, rbradford commented
> @rbradford Should I open a Github issue to discuss alternatives to initialize CpuManager before MemoryManager? Or we can continue the discussion as part of this PR?

You could explain your problem, rather than jumping to a solution, on your existing issue for the feature (#4761)

2022-12-01 16:51 UTC, rbradford commented
Obsoleted - see #4761

2022-12-01 16:51 UTC, closed without merging