ch-remote: Add support for vmm.ping
cloud-hypervisor/cloud-hypervisor pull request #4975
Opened 2022-12-04 12:53 UTC by ZhangShuaiyi

Add vmm-ping subcommand to ch-remote.

2022-12-04 14:12 UTC, liuw commented
@ZhangShuaiyi there is no need to keep creating new PRs to fix issues. You can just do a force push the your source branch. Github will handle things correctly.

2022-12-05 05:33 UTC, ZhangShuaiyi commented
>

2022-12-05 09:33 UTC, sboeuf requested changes

2022-12-05 09:33 UTC, sboeuf commented on src/bin/ch-remote.rs
> +        }
Please simplify as follows:
```suggestion
        Some("ping") => {
            simple_api_full_command(&mut socket, "GET", "vmm.ping", None)
                .map_err(Error::ApiClient)
        }
```

2022-12-05 09:33 UTC, sboeuf commented on src/bin/ch-remote.rs
> +        .subcommand(Command::new("vmm-ping").about("Request the VMM API server status"));
```suggestion
.subcommand(Command::new("ping").about("Ping the VMM to check for API server availability"));
```

2022-12-05 11:09 UTC, sboeuf approved these changes

2022-12-05 12:49 UTC, rbradford approved these changes

2022-12-05 15:44 UTC, likebreath approved these changes

2022-12-05 15:45 UTC, merged