docs: Consolidate arm64 doc into README/building.md/uefi.md
cloud-hypervisor/cloud-hypervisor pull request #4991
Opened 2022-12-08 06:16 UTC by MrXinWang

Fixes: https://github.com/cloud-hypervisor/cloud-hypervisor/issues/4984

Currently marking this PR as a draft because @michael2012z will double check the Arm related commands in the doc to make sure they still work. But comments are welcomed :) @rbradford @sboeuf.

Also I split the PR to several commits for easier review. Feel free to ask a squash if it is needed when committing.

2022-12-08 12:12 UTC, michael2012z commented
Thanks, @MrXinWang . Yes, it's good to cross-verify the commands by different persons.

But it's a running week to me. I need to defer testing the new commands 1 or 2 days.

2022-12-11 06:13 UTC, michael2012z requested changes

2022-12-12 02:38 UTC, MrXinWang commented on README.md
> +- On development boards that have constrained RAM resources, if the creation of
Done

2022-12-12 02:39 UTC, MrXinWang commented on README.md
> +Cloud Hypervisor supports direct kernel boot (the x86_64 kernel requires the kernel
Done

2022-12-12 02:40 UTC, MrXinWang commented on README.md
> +For x86_64, The `vmlinux` kernel image will then be located at
done

2022-12-12 02:40 UTC, MrXinWang commented on README.md
> +For AArch64, The `Image` kernel image will then be located at
done

2022-12-12 05:29 UTC, michael2012z approved these changes

2022-12-12 16:16 UTC, likebreath approved these changes

2022-12-12 16:43 UTC, rbradford commented on README.md
> +- On development boards that have constrained RAM resources, if the creation of
I'm not sure this is still a valid concern. The issue with `MAP_PRIVATE` and `memfd_create` was the cause of this problem. Obviously if you try and create VMs with a total memory greater than your available RAM you will have issues but those issues are not architecture dependent. I  think this whole paragraph can be removed.

2022-12-12 22:27 UTC, rbradford commented on README.md
> +- On development boards that have constrained RAM resources, if the creation of
@MrXinWang I think you accidentally resolved this thread. I don't think the paragraph talking about swap makes sense and it's not an aarch64 specific issue anyway.

2022-12-13 02:38 UTC, MrXinWang commented on README.md
> +- On development boards that have constrained RAM resources, if the creation of
Hi @rbradford 

> I think you accidentally resolved this thread.

I am really sorry.

> I don't think the paragraph talking about swap makes sense and it's not an aarch64 specific issue anyway.

I think Michael is also in favor of dropping this so I removed this whole paragraph. Thanks for your review.

2022-12-13 13:38 UTC, rbradford approved these changes

2022-12-13 13:38 UTC, merged

2022-12-13 13:38 UTC, rbradford commented
Thank you!

2022-12-15 16:23 UTC, rbradford commented
@MrXinWang Perhaps you could update the website to match: https://github.com/cloud-hypervisor/cloud-hypervisor.github.io ?

2022-12-17 11:16 UTC, MrXinWang commented
Hi @rbradford, sure, I can have a look.