Add ratelimit counter for virtio device
cloud-hypervisor/cloud-hypervisor pull request #5407
Opened 2023-04-25 11:51 UTC by zhuangel

Now cloud hypervisor support rate limit for virtio block device IO and virtio net device TX/RX, but no counter or log when block IO / net IO exceeds the rate limit, this patch adds counter for the rate limit events, so that we could track when and how many times block IO / net IO exceeds limit, then we may adjust the rate limit configurations.

2023-04-26 09:51 UTC, rbradford reviewed
Can you improve on the commit message of the "why". I'm not sure I really understand what this counter tells you. Surely a more useful counter is the number of frames/bytes rejected due to exceeding the rate limit?

2023-04-26 14:11 UTC, zhuangel commented
> Can you improve on the commit message of the "why". I'm not sure I really understand what this counter tells you. Surely a more useful counter is the number of frames/bytes rejected due to exceeding the rate limit?

Thanks, Rob, I have updated the commit message, we use these counter to find out whether the VM IO exceeds limits, then do configuration adjustment base it.

2023-04-28 04:24 UTC, zhuangel commented
> Surely a more useful counter is the number of frames/bytes rejected due to exceeding the rate limit?

Once the network traffic or block IO exceeds the rate limit, it is difficult to know exactly how many requests (frames/bytes) are being throttled, including requests buffered in the vring and new requests coming.

So, maybe just the rate limit count is enough for us, do you have any other thoughts.

2023-05-26 09:21 UTC, zhuangel commented
Hi @rbradford, I reset the PR according to the latest mainline, any comments that need to be addressed, thanks.

2023-05-31 21:44 UTC, likebreath requested changes
Looks like the motivation of this PR is trying to add a feature to the VMM to assist users to set rate limiter threshold appropriately based on their workloads. If my above understanding is correct, I think extending rate-limiter to generate these metrics is not the right way to go, as we don't want to bloat rate-limiter's functionality. Instead, it is better to add dedicate features to generate these metrics that you find helpful.

I would suggest you to open an GitHub issue to describe the problem you are trying to solve (e.g. the motivation) along with your proposed solution first, so that the community can provide feedback and ideas.

Any context I am missing, please let me know. Thank you for the contributions.

2023-06-01 17:30 UTC, zhuangel commented
> Looks like the motivation of this PR is trying to add a feature to the VMM to assist users to set rate limiter threshold appropriately based on their workloads. If my above understanding is correct, I think extending rate-limiter to generate these metrics is not the right way to go, as we don't want to bloat rate-limiter's functionality. Instead, it is better to add dedicate features to generate these metrics that you find helpful.
> 
> I would suggest you to open an GitHub issue to describe the problem you are trying to solve (e.g. the motivation) along with your proposed solution first, so that the community can provide feedback and ideas.
> 
> Any context I am missing, please let me know. Thank you for the contributions.

Thanks, I file issue about this, [5479](https://github.com/cloud-hypervisor/cloud-hypervisor/issues/5479)

2023-06-05 21:09 UTC, closed without merging