add memory bind policy
cloud-hypervisor/cloud-hypervisor pull request #5460
Opened 2023-05-24 06:38 UTC by zhangylc

cloud-hypervisor \
-vvv \
--cpus boot=1 --serial tty --console off --seccomp false \ --log-file /tmp/ch-fw.log \
--kernel /usr/share/cloud-hypervisor/ovmf.fd \
--disk path=/home/zhangyanlin/centos_8.2.ch.img.base \ --memory size=0 \
--memory-zone id=mem0,hugepages=on,size=4G,policy=1,host_numa_node=0 \ --numa guest_numa_id=0,memory_zones=mem0

The value of "policy": 0-->MPOL_DEFAULT, 1-->MPOL_PREFERRED, 2-->MPOL_BIND, 3-->MPOL_INTERLEAVE

2023-05-25 17:43 UTC, likebreath requested changes
This strict mbind mode was chosen by design. Quote from the code base comments:

```
            // MPOL_BIND is the selected mode as it specifies a strict policy
            // that restricts memory allocation to the nodes specified in the
            // nodemask.
```

2023-05-25 17:43 UTC, closed without merging

2023-05-26 02:33 UTC, zhangylc commented
@likebreath 
> This strict mbind mode was chosen by design. Quote from the code base comments:
> 
> ```
>             // MPOL_BIND is the selected mode as it specifies a strict policy
>             // that restricts memory allocation to the nodes specified in the
>             // nodemask.
> ```
Why not user cannot change this mode to preferred, there is no enough memory on the first node and there is enough memory on  the second node. if we specify the vm on the first node with strict mode, the vm cannot start.  The preferred mode will ensure the vm can start except for the preferred node (if we specify the first node as the preferred node).
So I think the preferred mode is needed for ensuring vm start normlly，the preferred node is just a better choice rather than a necessary choice.

2023-05-31 04:27 UTC, zhangylc commented
> @zhangylc This is exactly the desired behavior of specifying NUMA policy for the guest memory zone. We would like to ensure the NUMA requirement from users is respected. Otherwise the VM will fail to start, so that users can review their NUMA requirement.
Ok, I get it. Thanks.

2023-05-31 04:28 UTC, zhangylc commented
> > Why not user cannot change this mode to preferred, there is no enough memory on the first node and there is enough memory on the second node. if we specify the vm on the first node with strict mode, the vm cannot start.
> 
> @zhangylc This is exactly the desired behavior of specifying NUMA policy for the guest memory zone. We would like to ensure the NUMA requirement from users is respected. Otherwise the VM will fail to start, so that users can review their NUMA requirement.

Ok, I get it. Thanks.