AArch64: Add UEFI based direct kernel boot support
cloud-hypervisor/cloud-hypervisor pull request #5982
Opened 2023-11-23 09:51 UTC by jongwu

UEFI boot on AArch64 has not completed, see issue #5981.
This PR tries to enable all of the uncompleted tasks on CH side.

- [x] Boot from RHF using "-firmware";
- [x] boot from RHF using "-frimware" and start kernel specified by "-kernel", need support in RHF, see [PR](https://github.com/cloud-hypervisor/rust-hypervisor-firmware/pull/297)
- [x] boot from EDK2 using "-firmware" and start kernel specified by "-kernel", need support in EDK2, patch in review [ml](https://edk2.groups.io/g/devel/message/93882?p=%2C%2C%2C20%2C0%2C0%2C0%3A%3Acreated%2C0%2Cjianyong%2C20%2C2%2C40%2C93715215)

2023-11-29 18:24 UTC, likebreath commented on vmm/src/vm.rs
> +            .read_exact_from(GuestAddress(kernel_addr), &mut kernel_image, kernel_size)
If this is why you have to use `#[allow(deprecated)]`, you can use its alternative `read_exact_volatile_from`. And this commit is a good reference: https://github.com/cloud-hypervisor/cloud-hypervisor/commit/d4892f41b3124e777724ed872fb9997b8a47c1fb

2023-12-02 08:19 UTC, michael2012z requested changes

2023-12-02 08:19 UTC, michael2012z commented on vmm/src/vm.rs
> +    fn load_pe_or(
I think we don't need to add yet another function. See the comment on `load_payload()`.

And some question regarding this code changes: 
- If I assign a kernel binary to `--firmware`, does the guest boots from that kernel? If yes, that's not expected.
- If I assign a kernel to `--firmware` and the same kernel to `--kernel`, does the guest boots?

2023-12-02 08:19 UTC, michael2012z commented on vmm/src/vm.rs
> +            }
Can we achieve the booting with both firmware and kernel simply in this way?
- Keep the implementation of `load_kernel`
- Invoke `Self::load_kernel(None, Some(kernel), memory_manager);` to load the kernel at first and invoke `Self::load_kernel(Some(firmware), None, memory_manager)` and return the `EntryPoint` of the firmware

2023-12-04 01:29 UTC, jongwu commented on vmm/src/vm.rs
> +        };
kernel image here servers as data passed to firmware to load. So, it should not be subjected to this definition. Just like initramfs does.

2023-12-04 15:24 UTC, michael2012z commented
Hi, @jongwu 

Here are my concerns on the code changes:
1. `load_kernel()` now becomes a wrapper of `load_pe_or()`. It is not necessary to introduce yet another function. 
2. The function name `load_pe_or` is confusing.
3. Kernel loading is done in 2 different functions: `load_payload()` and `load_kernel_to_mem()`
4. For `KernelInfo`, it's better to avoid introducing a AArch64 specific struct. And it's very similar to `InitramfsConfig`.

For 1, 2 and 3, is it better to improve in this way?

- Rename `load_pe_or()` to `load_booting_binary()`
- Pass the binary and target address to `load_booting_binary()`, the binary could be a kernel or a firmware. Keep the current logic in it: Try loading as PE at first, if failed try loading as firmware.
```
fn load_booting_binary(
        binary: Option<File>,
        address: GuestAddress,
        memory_manager: Arc<Mutex<MemoryManager>>,
    ) -> Result<EntryPoint> ...
```

- Remove `load_kernel()`
- Invoke `load_booting_binary()` from `load_payload()`, the pseudo code is like:
```
    match (&payload.firmware, &payload.kernel) {
            (Some(firmware), None) => {
                Self::load_booting_binary(Some(firmware), arch::layout::UEFI_START, memory_manager)
            }
            (None, Some(kernel)) => {
                Self::load_booting_binary(Some(kernel), arch::layout::KERNEL_START, memory_manager)
            }
            (Some(firmware), Some(kernel)) => {
            	let kernel_addr = Calculate the target kernel address that the firmware needs;
            	_ = Self::load_booting_binary(Some(kernel), kernel_addr, memory_manager);
                Self::load_booting_binary(Some(firmware), arch::layout::UEFI_START, memory_manager)
            }
```
- In `system_configure()`, calculate the kernel target address and size for FDT, but do not load it into guest memory.

2023-12-05 10:59 UTC, jongwu commented
Thanks @michael2012z -, Great refactor.

I find a issue. PE loader will load kernel to some other place than the address passed to it and will do lots of check that no need for my case.  What I need is that load kernel image as a overall data into memory without unpacking it just like loading initramfs.
So, I need introduce a new loader or refact then reuse "load_initramfs". Which do you perfer?

2023-12-06 05:53 UTC, michael2012z commented
> I find a issue. PE loader will load kernel to some other place than the address passed to it and will do lots of check that no need for my case. What I need is that load kernel image as a overall data into memory without unpacking it just like loading initramfs. So, I need introduce a new loader or refact then reuse "load_initramfs". Which do you perfer?

In that case, I prefer to refactor `load_initramfs()` and `InitramfsConfig` for general usage covering initramfs and kernel image. In this way, we also resolved the problem of introducing a new KernelConfig, right?

2023-12-06 05:57 UTC, jongwu commented
> In that case, I prefer to refactor `load_initramfs()` and `InitramfsConfig` for general usage covering initramfs and kernel image. In this way, we also resolved the problem of introducing a new KernelConfig, right?

Make sense. Let me try this way.

2023-12-09 08:38 UTC, michael2012z commented on vmm/src/vm.rs
> +        let address = if is_top { top_addr } else { top_addr - offset };
This logic is only for AArch64, X86_64 has nothing with `top_addr` and `is_top`. Is it better if you calculate the address on the caller side and keep the logic of this function simple? Specifically:

1. Replace the parameter `is_top: bool,` with `addr: u64`
2. In this function, simply load the file to the specified `addr`
3. On X86_64, pass `arch::initramfs_load_addr()` when calling this function
4. On AArch64, apply your logic to determine the address in `configure_system()` before calling this function

2023-12-09 08:38 UTC, michael2012z commented on arch/src/lib.rs
> +pub struct BootFileConfig {
The name `BootFileConfig` sounds too generic, but I am not good at naming.

Any better idea for the name?

2024-01-16 19:04 UTC, likebreath commented
Closing due to no activities. Please re-open if needed. Thank you.

2024-01-16 19:04 UTC, closed without merging