tests: test_api_dbus_and_http_interleaved: use event monitor
cloud-hypervisor/cloud-hypervisor pull request #5992
Opened 2023-11-29 15:30 UTC by rmstoi

See: #5127

2023-11-29 15:57 UTC, rbradford approved these changes

2023-11-29 17:31 UTC, likebreath requested changes
I don't think this is the right way to replace `sleep()` with event monitor for waiting a certain event. `check_*_events_*` functions are for checking if events are expected to ensure event monitoring itself is working.

You will need to add a function like `wait_for_event(event: &str, timeout: i32) -> bool` that takes inputs `event` (the name of the event you are waiting for) and `timeout`  for waiting the event and returns `True` if and only if the `event` happens within the `timeout`.

Also keep in mind, you will need to double check the event you are waiting for is actually reported after the completion of the event (like this `shutdown` event) instead of only after the start of the event (like `resize`).

#5984 has the same problem and needs to be fixed.

2023-12-04 17:34 UTC, rmstoi commented
> I don't think this is the right way to replace `sleep()` with event monitor for waiting a certain event. `check_*_events_*` functions are for checking if events are expected to ensure event monitoring itself is working.
> 
> You will need to add a function like `wait_for_event(event: &str, timeout: i32) -> bool` that takes inputs `event` (the name of the event you are waiting for) and `timeout` for waiting the event and returns `True` if and only if the `event` happens within the `timeout`.
> 
> Also keep in mind, you will need to double check the event you are waiting for is actually reported after the completion of the event (like this `shutdown` event) instead of only after the start of the event (like `resize`).
> 
> #5984 has the same problem and needs to be fixed.

Could `check_latest_events_exact` be used instead of implementing new `wait_for_event`?

2023-12-04 18:31 UTC, likebreath commented
> > I don't think this is the right way to replace `sleep()` with event monitor for waiting a certain event. `check_*_events_*` functions are for checking if events are expected to ensure event monitoring itself is working.
> > You will need to add a function like `wait_for_event(event: &str, timeout: i32) -> bool` that takes inputs `event` (the name of the event you are waiting for) and `timeout` for waiting the event and returns `True` if and only if the `event` happens within the `timeout`.
> > Also keep in mind, you will need to double check the event you are waiting for is actually reported after the completion of the event (like this `shutdown` event) instead of only after the start of the event (like `resize`).
> > #5984 has the same problem and needs to be fixed.
> 
> Could `check_latest_events_exact` be used instead of implementing new `wait_for_event`?

No. I explained that in the comment you quoted. Please let me know if you any questions. 

Closing the PR now. Please open a new one with the `wait_for_event()` method explained above. Thanks.

2023-12-04 18:31 UTC, closed without merging