block: qcow: support compressed image
cloud-hypervisor/cloud-hypervisor pull request #6058
Opened 2023-12-26 03:46 UTC by dogonthemoon

1 Introduce ClusterType, and support compressed image(zlib based compression). 
2 Chose libdeflater as the decompression library, it performs best.

2023-12-26 07:28 UTC, dogonthemoon commented
@rbradford I'm sorry, i don't know how to add reviewers for this pull request, would you like to review it?

2023-12-28 10:13 UTC, rbradford requested changes
I'm not sure if we really want this functionality - we've been discussing removing QCOW2 support in general as it is complex code that nobody on the team has an interesting in maintaining.

Also I wouldn't want use to use the libdeflater crate and prefer a native Rust implementation over one that incorporates a library dependency.

2023-12-28 10:13 UTC, rbradford commented on block/Cargo.toml
> +libdeflater = "1.19.0"
The list of crates should be in lexical order.

2023-12-28 10:13 UTC, rbradford commented on block/src/qcow/mod.rs
> +extern crate libdeflater;
This is not required with our version of Rust.

2023-12-29 10:27 UTC, dogonthemoon commented
> I'm not sure if we really want this functionality - we've been discussing removing QCOW2 support in general as it is complex code that nobody on the team has an interesting in maintaining.
> 
> Also I wouldn't want use to use the libdeflater crate and prefer a native Rust implementation over one that incorporates a library dependency.

Yes I agree, QCOW2 has complex code, but it has some very import features that makes it stay alive, including this compression feature.

A native Rust implementation about decompression, would you like to give me more suggestion? 

thank you very much!

2024-02-28 19:39 UTC, closed without merging