docs: Update instructions to build debug TD-SHIM
cloud-hypervisor/cloud-hypervisor pull request #6077
Opened 2024-01-04 15:34 UTC by jinankjain

Current instructions are incorrect and there is now a new profile called dev-opt to build the debug version of TD-SHIM.

2024-01-04 17:15 UTC, likebreath requested changes
What's the version of the td-shim you have been using?

As mentioned explicitly in the document, the instructions were based on specific versions of the software stack that was tested. For td-shim, it is revision https://github.com/confidential-containers/td-shim/tree/66bb33451befbf1291abe3cfea7ee9e99d922b0d.

To update the building instructions, we will also need to update the revision information and validate the updated version works. I can help with validation part.

2024-01-05 03:21 UTC, jinankjain commented
@likebreath can you please try testing the latest release of TD-SHIM https://github.com/confidential-containers/td-shim/releases/tag/v0.8.0?

2024-01-05 17:29 UTC, likebreath commented
> @likebreath can you please try testing the latest release of TD-SHIM https://github.com/confidential-containers/td-shim/releases/tag/v0.8.0?

Tested and it is working fine. Please update the documentation with this version of td-shim. Also, for the building instructions, it can be simplified via using `cargo image --release` (for release) or `cargo image` (for debug) [1].

[1] https://github.com/confidential-containers/td-shim/tree/v0.8.0?tab=readme-ov-file#use-xtask-to-build-tdshim-image

2024-01-08 17:00 UTC, likebreath reviewed
You forgot to update the following build instruction `git checkout 66bb33451befbf1291abe3cfea7ee9e99d922b0d`

2024-01-08 23:10 UTC, merged