vmm: use trait objects for API actions
cloud-hypervisor/cloud-hypervisor pull request #6081
Opened 2024-01-05 23:28 UTC by alyssais

Uses of the old ApiRequest enum conflated two different concerns: identifying an API request endpoint, and storing data for an API request.  This led to ApiRequest values being passed around with junk data just to communicate a request type, which forced all API request body types to implement Default, which in some cases doesn't make any sense — what's the "default" path for a vhost-user socket?  The nonsensical Default values have led to tests relying on being able to use nonsensical data, which is an impediment to adding better validation for these types.

Rather than having API request types be represented by an enum, which has to carry associated body data everywhere it's used, it makes more sense to represent API request types as trait objects.  These can have an associated type for the type of the request body, and this makes it possible to pass API request types and data around as siblings in a type-safe way without forcing them into a single value even where it doesn't make sense.  Trait objects also give us dynamic dispatch, which lets us get rid of several large match blocks.

2024-01-06 01:07 UTC, alyssais commented
Not sure what to do about fuzzing… the new code structure doesn't allow for just pulling out the response sender and sending a null response.  I could turn ApiRequest into a struct that exposed the response sender, but that seems like a lot of effort to go to for something that would only be used by the fuzzer…

2024-01-09 15:31 UTC, rbradford commented
Seems reasonable to drop the fuzzing if needed. Looks like something went awry with the vm.counters API call.

2024-01-09 23:36 UTC, alyssais commented
> Seems reasonable to drop the fuzzing if needed.

Done.

> Looks like something went awry with the vm.counters API call.

Aha yes, there were some copy/paste errors between all the API handlers.  I've gone through the diff now and made sure that the Ok/Err enum wrapping matches what it was before for every request now.

2024-01-10 10:44 UTC, rbradford approved these changes, later dismissed

2024-01-10 18:31 UTC, likebreath requested changes
My main reservation is about dropping the fuzzer on http. The fuzzer is pretty valuable for the security of this component and found a previous vulnerability. 

I will have to wait for next week to take a look at this. Mark it as `Request changes` temporarily. Thanks for your patience.

2024-01-11 09:24 UTC, rbradford commented
> My main reservation is about dropping the fuzzer on http. The fuzzer is pretty valuable for the security of this component and found a previous vulnerability.

That's an excellent reason to keep it - we don't want to regress on that!

2024-01-11 18:24 UTC, alyssais commented
I think I've figured out a way to make fuzzing work.  Instead of having the fuzzer implement the top-level handling of the API, I've made a trait with all the `Vmm::vm_*` functions called by API methods, so the fuzzer can provide its own stub implementations of those.  This adds a bit of boilerplate, but it should let us keep fuzzing intact.

2024-01-17 00:02 UTC, likebreath approved these changes
Good work. Thank you for the contribution.

2024-01-17 10:19 UTC, rbradford approved these changes

2024-01-17 10:20 UTC, merged