vmm: Don't generate ACPI tables in case of SEV-SNP guest
cloud-hypervisor/cloud-hypervisor pull request #6179
Opened 2024-02-08 14:40 UTC by jinankjain

Since the ACPI tables are provided via IGVM file in case of SEV-SNP guest. So, we should not generate it as part of CloudHypervisor process.

2024-02-09 17:52 UTC, likebreath requested changes

2024-02-09 17:52 UTC, likebreath commented on vmm/src/vm.rs
> +                let rsdp_addr = if self.sev_snp_enabled {
You don't need to add this flag to the `Vm` struct, as you can query `self.config.lock().unwrap().is_sev_snp_enabled();`.

2024-02-13 18:39 UTC, russell-islam commented
LGTM

2024-02-13 19:29 UTC, likebreath approved these changes

2024-02-13 19:29 UTC, merged