Implement hypervisor agnostic variant of definitions from kvm_bindings
cloud-hypervisor/cloud-hypervisor pull request #6361
Opened 2024-04-05 13:25 UTC by jinankjain

Some of these structs were left out on aarch64 when we were trying to unify CloudHypervisor binaries for MSHV and KVM. Currently we are using the structs defined in kvm_bindings which won't work for MSHV. Thus, define hypervisor agnostic variants for these structs.

2024-04-08 09:05 UTC, jinankjain commented
@likebreath Things will start compiling for ARM64 once this PR lands along with PR for vfio crate https://github.com/rust-vmm/vfio/pull/43. Once both the PRs are in mainline, I will update the github CI scripts to add compile test for aarch64 and MSHV.

2024-04-15 18:39 UTC, likebreath requested changes
Thank you for the contribution. One general comment. I believe the generic (hypervisor-agnostic) struct should be simpler, e.g. a enum struct that is a wrapper of the underlining structs from  kvm_bindings and mshv_bindings crate. In such way, you don't need to expose details of the struct from the generic struct, and easier to maintain.  A good reference is:

https://github.com/cloud-hypervisor/cloud-hypervisor/blob/b5c5e9b34b54c9b9c681a7eac332cc120198c95d/hypervisor/src/lib.rs#L153-L169

2024-04-15 18:41 UTC, likebreath commented
For future references, I also want to mention that this will be (another) breaking change for live upgrade on top of #6370.

2024-04-26 21:17 UTC, likebreath commented
Close for no activities for two weeks. Please reopen if needed.

2024-04-26 21:17 UTC, closed without merging