Use thiserror throughout codebase
cloud-hypervisor/cloud-hypervisor pull request #6376
Opened 2024-04-09 22:29 UTC by SamrutGadde

We modified the whole codebase to utilize thiserror, improving error reporting. We used existing error information whenever possible and wrote our own error messages whenever necessary.

See #1910

2024-04-09 23:56 UTC, liuw commented
If the main branch is updated while you're working on your work, you should rebase you work onto it. Please don't create a merge commit in your feature branch.

2024-04-10 07:30 UTC, rbradford commented
Wow - thank you so much for your contribution :rocket:  - could you please split it into separate commits by package (or even further subdivisions with a second colon e.g. `vmm: config: Use thiserror for errors` - I spotted a few other items and I will put those through the review.

2024-04-10 07:35 UTC, rbradford commented on block/src/qcow/mod.rs
> +    #[error("failed to read pointers: {0}")]
Most of the messages start with a capital letter - i.e. sentence case - thee should be the same.

2024-04-17 15:47 UTC, rbradford requested changes
Perhaps split this PR up into chunks of 4 or 5 commits - will be easier to review and you will get better feedback?

2024-04-17 15:47 UTC, rbradford commented on api_client/src/lib.rs
> +use thiserror::Error;
This should be squashed with the change that added it.

2024-04-17 15:47 UTC, rbradford commented on api_client/Cargo.toml
> +thiserror = "1.0.52"
Good - adding it the commit that uses it - but t comes before v in the alphabet so they should be the other way around.

2024-04-17 15:47 UTC, rbradford commented on arch/src/aarch64/fdt.rs
> +    #[error("Failure in writing FDT in memory")]
Still need to fix it so that the underlying error is shown.

2024-04-17 15:47 UTC, rbradford commented on Cargo.toml
> +fmt = "0.1.0"
This crate isn't what you want...

2024-04-17 22:33 UTC, KshitijKapoor8 commented
> Perhaps split this PR up into chunks of 4 or 5 commits - will be easier to review and you will get better feedback?

Hey, sorry, we were just trying to split up the code from before into separate commits per package as you mentioned. We have not implemented the functional changes you told us about yet, but we are working on that asap (will definitely keep that to 4-5 commits). Sorry for any confusion and inconvenience!

2024-04-26 18:30 UTC, rbradford commented
Ping? What's the status on this? As you can see you've got some conflicts. I suggest you extract a subset of the commits into a new PR and submit that for review.

2024-04-26 20:12 UTC, SamrutGadde commented
Sorry for the delay, would you recommend that we open multiple PRs with a few commits at a time for easier review? Will definitely get this finished quickly.

2024-05-01 09:03 UTC, closed without merging