Fix memory region api
cloud-hypervisor/cloud-hypervisor pull request #6670
Opened 2024-08-17 11:18 UTC by Pivnoy

Fix #6547

Make private fields of ```UserMemoryRegin```.
Mark ```make_user_memory_region``` as ```unsafe```, add relevant comments

2024-08-17 11:29 UTC, alyssais requested changes

2024-08-17 11:29 UTC, alyssais commented on hypervisor/src/kvm/mod.rs
>      /// Creates a memory region structure that can be used with {create/remove}_user_memory_region
A safety doc comment is supposed to explain the invariants the function requires users to ensure — not just to explain what the function does, which should go above the safety comment.

2024-08-19 07:16 UTC, alyssais commented
I'm not familiar with this API, so I might have missed something, but why does the caller need to guarantee the validity of `slot`?  What's unsafe about passing an invalid slot and getting an error back?  I'm also not sure about guest_phys_addr — it's not immediately clear to me that that would be unsafe in Rust terms either.

Ideally the safety comment would describe what specifically the caller needs to guarantee, rather than just "validity" — maybe a maintainer could help explain those invariants if you're not sure.

2024-08-23 16:42 UTC, rbradford commented
Thank you for looking at this change - i'm not really sure this is particularly helpful. Labelling this method as unsafe doesn't help since there is no "safe" way to do this in lieu. Instead it just requires adding extra unsafe declarations around the code making it unnecessarily messy. The use of unsafe in API is to make sure the caller takes extra steps (i.e. to force the developer to take time and double check their work) however I don't think that is useful in this case.

2024-08-24 13:56 UTC, alyssais commented
> Thank you for looking at this change - i'm not really sure this is particularly helpful. Labelling this method as unsafe doesn't help since there is no "safe" way to do this in lieu. Instead it just requires adding extra unsafe declarations around the code making it unnecessarily messy. The use of unsafe in API is to make sure the caller takes extra steps (i.e. to force the developer to take time and double check their work) however I don't think that is useful in this case.

I strongly disagree that Cloud Hypervisor should contain methods that are known to be unsafe, but not marked as such.  `unsafe` has a clear meaning that should be applied consistently across different Rust codebases — this is critical for Rust developers to be able to produce sound code while moving between different projects.  It's common for there to be no safe equivalent to unsafe functions.

`unsafe` is not just useful when writing code, it's also useful when debugging it, and that's a situation where it's very likely that the person doing the debugging is not familiar with the code enough to know about a deliberate convention of not marking functions known to be unsafe.  One of the soundness issues (#6647) I found in Cloud Hypervisor recently was due to incorrect use of a function that was known to have preconditions, but not marked as unsafe.  If the rules of `unsafe` had been correctly followed, that issue couldn't have happened.

2024-09-03 14:42 UTC, rbradford commented
> > Thank you for looking at this change - i'm not really sure this is particularly helpful. Labelling this method as unsafe doesn't help since there is no "safe" way to do this in lieu. Instead it just requires adding extra unsafe declarations around the code making it unnecessarily messy. The use of unsafe in API is to make sure the caller takes extra steps (i.e. to force the developer to take time and double check their work) however I don't think that is useful in this case.
> 
> I strongly disagree that Cloud Hypervisor should contain methods that are known to be unsafe, but not marked as such. `unsafe` has a clear meaning that should be applied consistently across different Rust codebases — this is critical for Rust developers to be able to produce sound code while moving between different projects. It's common for there to be no safe equivalent to unsafe functions.
> 
> `unsafe` is not just useful when writing code, it's also useful when debugging it, and that's a situation where it's very likely that the person doing the debugging is not familiar with the code enough to know about a deliberate convention of not marking functions known to be unsafe. One of the soundness issues (#6647) I found in Cloud Hypervisor recently was due to incorrect use of a function that was known to have preconditions, but not marked as unsafe. If the rules of `unsafe` had been correctly followed, that issue couldn't have happened.

Okay - I agree that there are probably bugs in the code due to mistakes with assumptions but i'm not 100% sure that labelling a function that just populates a struct as unsafe is useful. That function itself can't have incorrect side effects since all it does (at least on KVM) is copy the values in.

2024-09-05 18:13 UTC, alyssais commented
> Okay - I agree that there are probably bugs in the code due to mistakes with assumptions but i'm not 100% sure that labelling a function that just populates a struct as unsafe is useful.

Well, it's our choice which APIs to mark as unsafe.  The APIs that consume the struct could be marked as unsafe instead, but it's very common for Rust abstractions to provide a wrapper type that is unsafe to construct with arbitrary values, so that the methods of that type can be safe, reducing the number of `unsafe` blocks required overall.

2024-12-05 23:24 UTC, closed without merging

2024-12-11 18:10 UTC, liuw commented
Are there anything we need to do regarding https://github.com/cloud-hypervisor/cloud-hypervisor/issues/6547?

Are people happy with leaving things as they are?

2024-12-18 15:44 UTC, rbradford commented
I think the PR just needs a rebase.