vmm: fix dma map after removing vfio device
cloud-hypervisor/cloud-hypervisor pull request #6891
Opened 2024-12-26 05:28 UTC by up2wing

Now cloud hypervisor do vfio dma map when first vfio container. However, vfio device will call Drop when remove all vfio device and vfio driver in kernel will unpin and unmap all guest pages. After this if new vfio device is added dma will fail because cloud hypervisor will not do vfio dma map again.

This patch adds a function to judge if vfio device exists, if all vfio device have been dropped we will do vfio dma map again.

2025-01-02 16:29 UTC, rbradford requested changes
Please open a bug report and outline what the issue is and how to reproduce this. I've tried to reverse engineer what the problem is from your commit message and and implementation but I can't work it out.

What I think you're saying is that when the last VFIO device is removed plugging a subsequent VFIO device fails. If that's the case the correct fix will be different to what you've implemented - either using an explicit reference count to how many devices are using the container or perhaps, neater, using `Weak`.

2025-01-22 18:57 UTC, likebreath commented
@up2wing Would you please follow up with @rbradford comments above and open a new issue? Close the PR for now.

2025-08-20 10:04 UTC, fslongjin commented
Hello! I've managed to replicate this issue. The method to reproduce the problem is as follows: bind a graphics card to the VFIO PCI driver and insert it into the virtual machine via hot plug. Everything works fine at this point. However, after hot unplugging it and attempting to reinsert, you'll find that nvidia-smi isn't functioning properly. Additionally, there are corresponding error messages in the dmesg logs:

<img width="1274" height="235" alt="698ac399-9632-48d1-bee1-478b4ad51bff" src="https://github.com/user-attachments/assets/38af8b7a-4f77-4c07-b5dd-38da38ccb5f4" />

If you hot-plug two GPUs and then unplug one before reinserting it, there won't be an issue. However, if you unplug both GPUs at the same time, reinserting them will definitely result in the abnormality as shown in the figure.
Moreover, when the GPU is hot-plugged into another new VM, it works perfectly fine.

So, the issue at hand is: after all vfio devices have been unplugged, when adding a new device, it's necessary to perform DMA mapping just as you would when initially inserting the vfio device.

The solution to this issue is actually quite straightforward: simply ensure that when a device is plugged in, and there are no vfio devices present, you just need to invoke DMA mapping at that time.

2025-08-20 19:46 UTC, rbradford commented
Oops. I don't think I meant to reopen this - @fslongjin can you please open an issue with details on how to reproduce this as you've shown above.

2025-08-20 19:46 UTC, closed without merging

2025-09-08 01:49 UTC, up2wing commented
> Oops. I don't think I meant to reopen this - @fslongjin can you please open an issue with details on how to reproduce this as you've shown above.

Sorry for the late reply due to being too busy at work.
I'll open an issue.